language: node_js

os:
  - linux
  - osx

osx_image: xcode12.2

node_js:
  - "node"

before_install:
  - npm install -g codecov

cache:
  directories:
    - "node_modules"

script:
    - npm run build
    - npm run test
    - codecov

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist -- --mac --win; fi
